Js sandbox
kontur-edu/Ulearn pull request #281
Opened 2023-06-30 05:29 UTC by Rozentor

Added multiple tests handling
Added js-sandbox

Not ready - formatting output
Do we need to beutify runner output?

2023-07-04 07:11 UTC, API-kernel requested changes

2023-07-13 06:37 UTC, API-kernel commented on src/Core/RunCheckerJobApi/RunningResults.cs
> +	public class TestInfo
Может вынести в отдельные классы, а то кажется файл сильно разросся. Я так-то тот еще фанат один класс один файл )

2023-07-13 06:37 UTC, API-kernel commented on src/Core/RunCheckerJobApi/RunningResults.cs
> +		public string ExpectedValue { get; set; }
Есть ощущение что эти данные нельзя получить из sanbox, и возможно это нужно будет делать где-то в обработчике обратного события

2023-07-13 06:40 UTC, API-kernel commented on src/Core/RunCheckerJobApi/RunningResults.cs
> +		public bool IsSuccessful { get; set; }
На одном из ревью преложили более удачное имя - IsPassed, если речь про тесты, IsEqual если речь идет про сравнение вывода. В нашем случае кажется это будет касаться только тестов, поэтому IsPassed подходит.

2023-07-13 06:47 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +const stopOnFirstFailedTest = argv.some(arg => arg === '--stopOnFirstFailedTest' || arg === '-sofft');
Почему тут проверятся наличие двух аргументов? Что-за sofft?

2023-07-13 06:50 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +      f.endsWith(".test.cjs") ||
Что-за файл тут добавился?

2023-07-13 06:56 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +  } else if (testResults && testResults.failures && testResults.failures.length > 0) {
Мне не нравится что при передаче аргумента меняется вывод. Давай сделаем вывод всегда одной структуры, т.е. выводить всегда вот такую структуру 

```
{
      verdict: "",
      compilationOutput: ``,
      output: ``,
      error: ``,
      tests: testResultInfos
}
```

2023-07-13 06:57 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +    for (const passTest of testResults.passes) {
А тут нельзя просто по ним всем пробежаться один раз?

2023-07-13 07:25 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +const stopOnFirstFailedTest = argv.some(arg => arg === '--stopOnFirstFailedTest' || arg === '-sofft');
Сокращение stopOnFirstFailedTest

2023-07-13 07:28 UTC, Rozentor commented on src/Core/RunCheckerJobApi/RunningResults.cs
> +		public string ExpectedValue { get; set; }
Либо тест знает какой ожидается результат, тогда в этоп поле очевидно какие данные будут
Либо lms потом сама сравнивает вывод, что странно

2023-07-13 07:39 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +  } else if (testResults && testResults.failures && testResults.failures.length > 0) {
Это нарушит старое поведение JS sandbox 
Ну да ладно

2023-07-13 07:43 UTC, Rozentor commented on src/Core/RunCheckerJobApi/RunningResults.cs
> +		public bool IsSuccessful { get; set; }
Ок

2023-07-13 07:43 UTC, Rozentor commented on src/Core/RunCheckerJobApi/RunningResults.cs
> +	public class TestInfo
Ок

2023-07-13 07:53 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +    for (const passTest of testResults.passes) {
Можно
Есть tests, он содержит теже самые тесты что и passes + failures. Порядок там вроде как строится из очереди проверки (1ый тест будет в tests[0] и т.д.)
Надо только подумать, как сделать чтобы если stopOnFirstFailure = true, мы в tests возвращали ТОЛЬКО первый неудачный тест или ничего вообще

2023-07-13 07:54 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +        output: failure.err.message,
Не совсем
Здесь будет само сообщение ошибки
+ у нас есть информация об названии теста
Обычно этого хватает

Прикреплю все поля в скрине
![image](https://github.com/kontur-edu/Ulearn/assets/36932390/00f3ee25-7cc9-444d-98ca-7f36dc511bab)
И сам тест
![image](https://github.com/kontur-edu/Ulearn/assets/36932390/135d0176-f06b-4e44-af6f-0fe47413c2db)

2023-07-13 07:57 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/js-sandbox/container/.dockerignore
> +**/node_modules
Я вижу процесс как
- на основе sandbox-ов ulearn-а создаются альтернативы, которые умеют запускать все тесты
- в один момент ulearn переводит 1 курс на новый сервис, а значит добавляет адаптер

Поэтому путать и помещать разные раннеры в 1 папку не вижу смысла
Мы лишь усложним, придется следить, правильный ли сандбокс подгружается в новый сервис, не установил ли он какой-нибудь старый из ulearn

2023-07-13 07:58 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/js-sandbox/container/.dockerignore
> +**/node_modules
Про копирование / изменения - согласен

2023-07-13 08:13 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +const stopOnFirstFailedTest = argv.some(arg => arg === '--stopOnFirstFailedTest' || arg === '-sofft');
node runner.mjs --stopOnFirstFailedTest
node runner.mjs -sofft

Идентичные команды

2023-07-13 08:16 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +const stopOnFirstFailedTest = argv.some(arg => arg === '--stopOnFirstFailedTest' || arg === '-sofft');
А зачем поддерживать два аргумента? + есть очень похожее слово soft, несколько напрягает, может все же один оставим? пусть длинное, зато понятно что делает. в т.ч. и в местах вызова

2023-07-13 08:17 UTC, API-kernel commented on src/Core/RunCheckerJobApi/RunningResults.cs
> +		public string ExpectedValue { get; set; }
А он в игноре где-то? я не вижу его чейнджах

2023-07-13 08:17 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +      f.endsWith(".test.cjs") ||
А он в игноре где-то? я не вижу его чейнджах

2023-07-13 08:18 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +  } else if (testResults && testResults.failures && testResults.failures.length > 0) {
вроде json ведь там, т.е. добавление ничего не ломает

2023-07-13 08:18 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +const stopOnFirstFailedTest = argv.some(arg => arg === '--stopOnFirstFailedTest' || arg === '-sofft');
Здесь я не готов за своё решение "бороться"
При написании был позыв добавления шортката :)
Следовал похожим подходам для cli программ, они часто добавляют сокращение

2023-07-13 08:19 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +      f.endsWith(".test.cjs") ||
https://github.com/kontur-edu/Ulearn/pull/281/files#diff-cbe706fd91af7b755b7447fc76eda27fe7e673d6847558b8e6b35d713c194b1c

2023-07-13 08:29 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +        output: failure.err.message,
Ок, давай пока так оставим. Были мысли что выводить хотелось точно также как бы это выводилось в боевых(рабочих) условиях

2023-07-13 08:32 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/js-sandbox/container/.dockerignore
> +**/node_modules
Ну да, там еще может вывод как-то будем менять... Ок, давай пока копировать. Вроде сами контейнеры не дожны сильно меняться, и поэтому не должно быть проблемы мерджить их потом.

2023-07-13 09:27 UTC, API-kernel commented on src/Core/RunCheckerJobApi/RunningResults.cs
> +		public string ExpectedValue { get; set; }
Это ведь не про случай тестов. это про сравнение вывода программы. И кажется что в этом случае проверка на стороне сервиса(АПИ) норм. Ну или я не так понял назначение полей ExpectedValue ActualValue

2023-07-13 09:33 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +        isPassed: !message,
А тут нет более явного признака? очень бы хотелось чтоб был )

2023-07-13 09:35 UTC, Rozentor commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +        isPassed: !message,
В Mocha err для пройденного теста это пустой объект {}
для провалившегося - { ..., err: string }

2023-07-13 09:43 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +      f.endsWith(".test.cjs") ||
За оснвоу был взять файл не из мастера, а из курса: https://git.skbkontur.ru/edu/basic-web/-/blob/b282c960fa7cb5cba2f9869812292325dbd2702a/ulearn/basic-web/TestsRunner/docker-test-runner.mjs

2023-07-13 09:52 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +    else for (const test of testResults.tests) {
Ох, очень опасная конструкция. Давай не поленимся обернуть в скобки, зато будет четкая структура и не будет неожиданностей если после for добавить еще код и потом гадать почему он не выполнился в ветке else

2023-07-13 10:03 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +        isPassed: !message,
Мне не очень нравится идея полагаться на пустую строку, кажется может быть ситуация когда текст будет пустым, но при этом тест не пройдён. Там нет некого state ну или как-то еще определить что тест провален? Вот [тут ](https://stackoverflow.com/questions/53206680/get-all-test-fails-from-mocha) вроде что-то пишут что есть чет такое

2023-07-13 10:17 UTC, API-kernel commented on src/CodeChecker/Docker-Sandboxes/js-sandbox/sample/src/docker-test-runner.mjs
> +        isPassed: !message,
Не, нету. Ок оставляем как есть.

2023-07-19 08:41 UTC, merged