ULEARN-1116 Модуль автопровеки кода. АПИ. Получение данных задания
kontur-edu/Ulearn pull request #290
Opened 2023-07-19 13:49 UTC by LuKas-03

Настройка и инициализация БД, контроллер заданий

2023-07-19 13:53 UTC, LuKas-03 commented on src/CodeChecker/Database/Repos/TextsRepo.cs
> +	public TextsRepo(CodeCheckerDatabaseContext codeCheckerDatabaseContext)
Имеющиеся репозитории не трогал, произошёл только ренейм. На данный момент они не используются

2023-07-20 05:40 UTC, API-kernel commented on src/CodeChecker/Api/EntryPoint.cs
>  			{
А как ты без указания порта смог локально поднять АПИ?)

2023-07-20 05:41 UTC, API-kernel commented on src/CodeChecker/Api/Installer.cs
> +	public static void Install(IWindsorContainer container, IVostokHostingEnvironment environment)
А как контроллеры попали в контейнер?

2023-07-20 05:42 UTC, API-kernel commented on src/CodeChecker/Api/Models/Exercises/ExerciseBuilder.cs
> +	public async Task<ExerciseDto?> BuildAsync(string teamName, string courseName, string exerciseName)
Есть стойкое ощущение что эта троица будет много где прокидываться, может сразу в record её оформим?

2023-07-20 05:46 UTC, Rozentor commented on src/CodeChecker/Database/Migrations/20230718112545_InitialCreate.cs
> +                name: "TextBlobs",
Хотя кажется легче оставить и забить :)

2023-07-20 05:47 UTC, API-kernel commented on src/CodeChecker/Api/Models/Exercises/ExerciseBuilder.cs
> +		var exerciseFile = exercise.XmlFileAsJson.CodeFiles.FirstOrDefault();
Кажется в имени XmlFileAsJson нет смысла упоминать что оно взято из XmlFile, да и тип вроде что это внутри некий json тоже. Нужно просто дать какое-то имя отражающее что хранится внутри. У меня в голову тлоько абстраутные штуки лезут, может у тебя лучше получится, у меня такие варианты: Props Meta Data MetaDescription ...

2023-07-20 05:49 UTC, API-kernel commented on src/CodeChecker/Api/Models/Exercises/ExerciseBuilder.cs
> +		var exerciseFile = exercise.XmlFileAsJson.CodeFiles.FirstOrDefault();
Я бы еще выделил в неких экстеншн или что-то еще, дабы не раскидывать по коду CodeFiles.FirstOrDefault();

2023-07-20 05:51 UTC, API-kernel commented on src/CodeChecker/Api/Models/Exercises/ExerciseBuilder.cs
> +			Code = "Console.WriteLine(\"Hello World!\");"
Может заглушку написать которая типа в драйв ходит, но пусть уже передаёт все необходимые параметры, и там уже замокать результат? Или может даже так сделать, что не падать если файла на диске нет, и пусть пустой пока будет Code

2023-07-20 05:56 UTC, API-kernel commented on src/CodeChecker/Api/Models/Exercises/ExerciseBuilder.cs
> +			MimeType = fileLanguageInfo.MimeType
Возможно MimeType нужно вычислять, ибо он не будет браться из xml, а это будет где-то внутренний справочник. 
Кажется что с вероятностью 85% будем monaco, поэтому можно посмотреть для него какой язык в него нужно передать чтобы он нас понял. Добавить пока можно для js pg(sql), html css python

2023-07-20 06:01 UTC, API-kernel commented on src/CodeChecker/Api/Models/Files/FileLanguageHelpers.cs
> +public static class FileLanguageExtensions
Рассиннхрон в именах с файлом произошел, кажется класс нужно переименовать

2023-07-20 06:04 UTC, API-kernel commented on src/CodeChecker/Database/appsettings.json
> +	"UlearnEnvironmentName": "local",
Желательно его не использовать, у нас есть Env в houston|vostok, желательно только им и обходится

2023-07-20 06:05 UTC, API-kernel commented on src/CodeChecker/Database/appsettings.local.json
> +	"database": "Host=localhost;Port=5432;Database=CodeChecker;Username=postgres;Password=postgres"
Давай этот файл засуним в игнор, и вот я думаю можно сделать одинаково как в песочнице, там `dev`  используется

2023-07-20 06:07 UTC, API-kernel commented on src/CodeChecker/Database/Repos/UserSolutionsRepo.cs
> +	private readonly CodeCheckerDatabaseContext codeCheckerDatabaseContext;
Контекст нельзя захватывать другими зависимостями, ибо они у нас все будут singletone, а контекст должен быть transient

2023-07-20 06:09 UTC, API-kernel commented on src/CodeChecker/Database/CodeCheckerDatabaseContext.cs
> +	public DbSet<TextBlob> Texts { get; set; }
Хочется поднять куда-то наверх, может поднимем?

2023-07-20 06:11 UTC, API-kernel commented on src/CodeChecker/Database/CodeCheckerDatabaseContextFactory.cs
> +public class DbFactory : IDesignTimeDbContextFactory<CodeCheckerDatabaseContext>
Локально кстати ведь строка подключения не берется из локального конфига, да?

2023-07-20 06:13 UTC, API-kernel commented on src/CodeChecker/Database/DatabaseSettings.cs
> +	public string Database { get; set; }
тут ожидал что-то из разряда connectionString... а почему не используется настройка?

2023-07-20 06:19 UTC, API-kernel commented on src/CodeChecker/Database/Models/CodeFile.cs
> +	public string SolutionCode { get; init; }
Кажется что тут должно быт что-то более обобщенное, типа просто сode или content

2023-07-20 06:22 UTC, API-kernel commented on src/CodeChecker/Database/Models/Course.cs
> +	[MaxLength(100)]
Чет несколько кажется странным что у всех трех строковых значений разный размер )

может у всех сделаем 255?

2023-07-20 06:24 UTC, API-kernel commented on src/CodeChecker/Database/Models/ICourse.cs
> +	int CourseId { get; set; }
В интерфейсах вроде нам не нужен set

2023-07-20 06:27 UTC, API-kernel commented on src/CodeChecker/Database/Models/Team.cs
> +public class Team : ITeam
давай как-то структурно разделим сущности контекста, вспомогательные модели, возможно интерфейсы тоже в отдельную папку

2023-07-20 06:29 UTC, API-kernel commented on src/CodeChecker/Database/Repos/ExerciseRepo.cs
> +		var db = new CodeCheckerDatabaseContext();
`await using var db = new CodeCheckerDatabaseContext();`

2023-07-20 06:31 UTC, API-kernel commented on src/CodeChecker/Database/CodeCheckerDatabaseContext.cs
> +		optionsBuilder.UseNpgsql(ApplicationConfiguration.Read<UlearnConfiguration>().Database, o => o.SetPostgresVersion(13, 2));
А почему тут вообще нужно указывать версию БД?

2023-07-20 06:59 UTC, LuKas-03 commented on src/CodeChecker/Api/Installer.cs
> +	public static void Install(IWindsorContainer container, IVostokHostingEnvironment environment)
[Вот так](https://github.com/kontur-edu/Ulearn/pull/290/files#diff-9fec56590411b07bc4e4f223aecb00902f6c891710e4df9dad61f533cace2695R26)

2023-07-20 09:39 UTC, LuKas-03 commented on src/CodeChecker/Database/CodeCheckerDatabaseContext.cs
> +		optionsBuilder.UseNpgsql(ApplicationConfiguration.Read<UlearnConfiguration>().Database, o => o.SetPostgresVersion(13, 2));
убрал

2023-07-20 09:45 UTC, LuKas-03 commented on src/CodeChecker/Database/DatabaseSettings.cs
> +	public string Database { get; set; }
используется, просто совпало что у `UlearnConfiguration` одноименное поле, поправил и тут и убрал использование модели конфигурации ulearn

2023-07-20 11:35 UTC, LuKas-03 commented on src/CodeChecker/Database/Migrations/20230718112545_InitialCreate.cs
> +                name: "TextBlobs",
Я так понял мы код вообще в базе хранить не будем. Решил всё таки удалить ненужные модельки, если что можно будет вернуть

2023-07-20 11:36 UTC, LuKas-03 commented on src/CodeChecker/Database/Repos/UserSolutionsRepo.cs
> +	private readonly CodeCheckerDatabaseContext codeCheckerDatabaseContext;
это репозиторий перенесенный с ulearn, решил удалить эти модели вместе с репозиториями

2023-07-20 12:23 UTC, LuKas-03 commented on src/CodeChecker/Database/Models/CodeFile.cs
> +	public string SolutionCode { get; init; }
тут скорее зависит от реализации CourseLoader. Вообще пока сделал `hasCreatorSolution`

2023-07-21 05:48 UTC, API-kernel commented on src/CodeChecker/Database/appsettings.local.json
> +	"database": "Host=localhost;Port=5432;Database=CodeChecker;Username=postgres;Password=postgres"
Кстати, возможно нужно вынести на уровень выше, и подключать этот файл на всех проектах и дабы он был один, а то придется дублировать локально настройки.

2023-07-24 12:57 UTC, LuKas-03 commented on src/CodeChecker/Database/CodeCheckerDatabaseContextFactory.cs
> +public class DbFactory : IDesignTimeDbContextFactory<CodeCheckerDatabaseContext>
теперь берётся

2023-07-25 06:41 UTC, Rozentor requested changes

2023-07-25 06:41 UTC, Rozentor commented on src/CodeChecker/Database/Entity/Course.cs
> +	public bool IsWebhookEnabled { get; set; }
Всегда включено - не нужно

2023-07-25 06:41 UTC, Rozentor commented on src/CodeChecker/Database/Entity/Interfaces/ICourse.cs
> +	bool IsWebhookEnabled { get; }
И здесь тоже не нужно

2023-07-25 06:41 UTC, Rozentor commented on src/CodeChecker/Database/Models/Exercises/ExerciseRoute.cs
> +	public override string ToString() => $"{TeamName}/{CourseName}/{ExerciseName}";
Ещё версия
 https://wiki.skbkontur.ru/pages/viewpage.action?pageId=707480280

2023-07-25 07:26 UTC, LuKas-03 commented on src/CodeChecker/Database/Models/Exercises/ExerciseRoute.cs
> +	public override string ToString() => $"{TeamName}/{CourseName}/{ExerciseName}";
мне кажется по необходимости можно будет добавить позже

2023-07-25 07:26 UTC, LuKas-03 commented on src/CodeChecker/Database/Entity/Course.cs
> +	public bool IsWebhookEnabled { get; set; }
поправил

2023-07-25 08:06 UTC, API-kernel commented on src/CodeChecker/Api/Api.csproj
> +      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.9" />
У нас не будет lazy-loading, кажется пакет можно убрать

2023-07-25 08:07 UTC, API-kernel commented on src/CodeChecker/Api/ApiApplication.cs
>  		builder.CustomizeWebApplication(webApplication =>
Давай удалим тоже сразу?

2023-07-25 08:11 UTC, API-kernel commented on src/CodeChecker/Api/Installer.cs
> +	public static void Install(IWindsorContainer container, IVostokHostingEnvironment environment)
Удостоверься что они в режиме singletone

2023-07-25 08:21 UTC, API-kernel commented on src/CodeChecker/Database/Models/Exercises/ExerciseRoute.cs
> +	public override string ToString() => $"{TeamName}/{CourseName}/{ExerciseName}";
Кажется версия сюда не впишется, да, давай со временем поймем...

2023-07-25 08:31 UTC, API-kernel commented on src/CodeChecker/Database/Models/Course.cs
> +	[MaxLength(100)]
У ветки еще осталось 64

2023-07-25 08:32 UTC, API-kernel commented on src/CodeChecker/Database/appsettings.local.json
> +	"database": "Host=localhost;Port=5432;Database=CodeChecker;Username=postgres;Password=postgres"
Не стал делать?

2023-07-25 08:35 UTC, API-kernel commented on src/CodeChecker/Database/CodeCheckerDbContext.cs
> +			Validator.ValidateObject(entity, validationContext);
А что тут происходит? Зачем эта уонструкция?

2023-07-25 08:48 UTC, API-kernel commented on src/CodeChecker/Database/appsettings.json
>  {
Давай для простоты деплоя сделаем так что тут все-таки будут переменные-замены, а тестовая строка подключения все-же уедет в appsettings.dev.json и засунем еще её в игнор.

2023-07-25 10:35 UTC, LuKas-03 commented on src/CodeChecker/Api/ApiApplication.cs
>  		builder.CustomizeWebApplication(webApplication =>
убрал метод ping, остальное нужно

2023-07-25 10:39 UTC, LuKas-03 commented on src/CodeChecker/Database/CodeCheckerDbContext.cs
> +			Validator.ValidateObject(entity, validationContext);
досталось от uLearn, удалил пока что

2023-07-25 11:37 UTC, LuKas-03 commented on src/CodeChecker/Api/Models/Files/FileLanguageData.cs
> +	private static Dictionary<FileLanguage, FileLanguageData> items = new Dictionary<FileLanguage, FileLanguageData>
соотвествует

2023-07-25 11:44 UTC, LuKas-03 commented on src/CodeChecker/Database/appsettings.json
>  {
не хочется убирать, чтобы был некий образец для ConnectionString, чтобы не нужно было никуда лезть и искать его при первом выкачивании проект

2023-07-25 11:44 UTC, LuKas-03 commented on src/CodeChecker/Database/appsettings.json
>  {
appsettings.dev.json и так в игноре

2023-07-25 13:03 UTC, LuKas-03 commented on src/CodeChecker/Database/appsettings.json
>  {
указал в readme

2023-07-25 13:05 UTC, LuKas-03 commented on src/CodeChecker/Api/Api.csproj
> +      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.9" />
сборка API разваливается без этого, пока отсавил, разберусь по в рамках другой задачи

2023-07-25 13:54 UTC, Rozentor approved these changes

2023-07-26 12:37 UTC, merged