Export controller optimization
kontur-edu/Ulearn pull request #291
Opened 2023-07-22 16:37 UTC by Defalt1878

2023-07-22 16:41 UTC, Defalt1878 commented
Насколько возможно оптимизированы запросы к базе данных. В виду множества GroupBy и соединения таблиц оптимизировать сильнее вряд ли помогут даже дополнительные индексы. Проблема в том что из базы тащится огромное число данных, соединить быстро и эффективно с помощью EF Core промлематично. Дальнейшую оптимизацию вижу лишь в переписывании LINQ на сырой SQL.

2023-07-24 18:53 UTC, Rozentor requested changes
Немного надо поправить

2023-07-24 18:53 UTC, Rozentor commented on src/Common/Extensions/EnumerableExtensions.cs
> +		}
Это странно :)

2023-07-24 18:53 UTC, Rozentor commented on src/Web.Api/Controllers/ExportController.cs
> +							.Where(login => login.LoginProvider == "ВКонтакте")
"Вконтакте" магическая константа
Вроде где-то вынесено было
Надо проверить, или вынести

2023-07-24 18:53 UTC, Rozentor commented on src/Web.Api/Controllers/ExportController.cs
> +			public string?[]? Answers;
(не ошибка)
?[]?
Я к такому не привык 0_о

2023-07-25 08:12 UTC, Defalt1878 commented on src/Web.Api/Controllers/ExportController.cs
> +							.Where(login => login.LoginProvider == "ВКонтакте")
Вынес

2023-07-25 10:59 UTC, merged