[BREAKING] Init CourseLoader, CourseLoader.Tests with simple course
kontur-edu/Ulearn pull request #297
Opened 2023-07-27 19:52 UTC by Rozentor

Extracted CommonApi
Small refactor in CodeChecker.Common JsonHelper file naming [BREAKING] Refactored database models, swapped Init migration Added schema with controller and in memory cache
Added webhook controller, copied from ulearn
Refactored repos after editing models
Added temp ping controller to check proxy via nginx-location
Added *mocked* FileShareClient, now it's just copy files locally

2023-07-28 21:08 UTC, Rozentor commented
TODO
----
FileShare
SecretKeysProvider
Git in CourseLoader Houston

2023-08-11 05:33 UTC, API-kernel commented on src/CodeChecker/Api/ApiApplication.cs
> +			webApplicationBuilder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options => { options.SerializerOptions.Converters.Add(new JsonStringEnumConverter()); });
Ой, строчки стали слишком длинные, неудобно такие читать/редактировать, остальные я бы тоже вернул как было, так они больше поддаются дальнейшему редактированию с минимальными модификациями

2023-08-11 05:40 UTC, API-kernel commented on src/CodeChecker/Api/Controllers/V1/ExerciseController.cs
> +		var exerciseRoute = new ExerciseRoute(course.TeamId, course.CourseId, course.LastPublishedCourseVersionId.Value, exerciseName);
Давай все же за ExerciseRoute, оставим то что мапится из роута, ибо имя на это и намекает

2023-08-11 05:40 UTC, API-kernel commented on src/CodeChecker/Api/Controllers/V1/ExerciseController.cs
> +		var team = await teamsRepo.GetByTeamNameAsync(teamName);
Давай это тоже сразу обобщим, это явно понадобится более чем в одно месте, под все я понимаю team, course, exercise. Пусть будет некая зависимость которая будет это строить по аутентичному ExerciseRoute

2023-08-11 05:45 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveGateway.cs
> +			new DriveContent(GetFullName(name), new MemoryStream(content), daysToLive: 30),
Раз константы уже дублируются, то кажется пришло время выделить их в настоящие константы

2023-08-11 05:46 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveNameHelper.cs
> +	public static string CourseZip(string teamName, string courseName, string versionAsString) => $"Teams/{teamName}/{courseName}/{versionAsString}.zip";
Давай как-то однотипно называть, давай тогда переименуем ZipFile в SolutionZip

2023-08-11 05:46 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveNameHelper.cs
> +	public static string CourseZip(string teamName, string courseName, string versionAsString) => $"Teams/{teamName}/{courseName}/{versionAsString}.zip";
Давай не будем играть с огнем, и в пути будем содержать все в нижнем регистре

2023-08-11 05:48 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveNameHelper.cs
> +	public static string CourseZip(string teamName, string courseName, string versionAsString) => $"Teams/{teamName}/{courseName}/{versionAsString}.zip";
string versionAsString я бы переименовал в просто string version, вроде и так видно что это строка )

2023-08-11 05:48 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/IDriveGateway.cs
> +	ContentUploadResult Upload(string name, byte[] content, int timeOutInSeconds = 10);
Думаешь мы где-то заходтим регулировать таймауты? Может просто в константу пока вынести внутри DriveGateway

2023-08-11 05:57 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Settings/DriveSettings.cs
> +	public int UploadTimeoutInSeconds { get; set; }
Может тогда не только на Upload сделать но и на Download, и просто обозвать TimeoutInSeconds

2023-08-11 06:04 UTC, Rozentor commented on src/CodeChecker/Api/ApiApplication.cs
> +			webApplicationBuilder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options => { options.SerializerOptions.Converters.Add(new JsonStringEnumConverter()); });
Это автоформатирование у меня так отработало
Вручную поменяю - автоформатирвоание перезатрет)

2023-08-11 08:26 UTC, API-kernel commented on src/CodeChecker/CodeChecker.CommonApi/BaseApplication.cs
> +			webApplicationBuilder.Host.ConfigureContainer<IWindsorContainer>((_, container) => { InstallWindsor(_, container, environment); });
Тут тоже замечу что слишком длинные строки

2023-08-11 08:46 UTC, API-kernel commented on src/CodeChecker/CodeChecker.CommonApi/BaseApplication.cs
> +	public override Task WarmupAsync(IVostokHostingEnvironment environment, WebApplication webApplication)
Возможно стоит убрать

2023-08-11 08:48 UTC, API-kernel commented on src/CodeChecker/CodeChecker.CommonApi/BaseInstaller.cs
> +public static class BaseInstaller
Я бы не сказал что это только к АПИ относится, это больше похоже на CodeChecker.Common

2023-08-11 08:53 UTC, API-kernel commented on src/CodeChecker/Database/Repos/TeamsRepo.cs
> +public class TeamsRepo : ITeamsRepo
Есть предложение как-то одинаково называть репозитории. Вроде в папке большинство названо в единственном числе, давай тут тоже так сделаем

2023-08-11 08:56 UTC, API-kernel commented on src/CodeChecker/Database/Repos/Interfaces/IExerciseRepo.cs
> +	Task AddRangeAsync(IEnumerable<Exercise> exercises);
Есть предложение, дабы как-то навести порядок среди хаоса, выбрать одну основную структуру для массивов, и преимущественно их использовать, и только при необходимости использовать другие типа. Кажется очень компактно удобно использоваться массивы, т.е. просто Exercise[].

2023-08-11 08:57 UTC, API-kernel commented on src/CodeChecker/Database/Repos/Interfaces/ICoursesRepo.cs
> +	public Task<List<Course>> GetAllCoursesAsync();
Тут тоже предлагаю заменить на массив, дабы не смущать к-вом угловых скобочек ну и для стандартизации

2023-08-11 08:58 UTC, API-kernel commented on src/CodeChecker/Database/Repos/ExerciseRepo.cs
> +	public async Task AddRangeAsync(IEnumerable<Exercise> exercises)
Можно сделать одним методом, кажется нет смысла держать два брата близнеца. Можно даже сделать через params

2023-08-11 09:03 UTC, API-kernel commented on src/CodeChecker/Database/Repos/CoursesRepo.cs
> +	public async Task PublishNewVersionAsync(int courseId, int courseVersionId)
Мне чет не очень нравится идея писать прям каждый раз метод для обновления каждого из полей... тут недалеко и до комбинаторного взрыва.

Может сделать как в UserExerciseSolutionRepo.UpdateAsync ?

2023-08-11 09:04 UTC, API-kernel commented on src/CodeChecker/Database/Repos/Interfaces/ICoursesRepo.cs
> +	public Task<Course?> GetCourseAsync(int teamId, string courseName);
Возвращать из репозитория сами сущности чревато вызова навигационных свойств, давай тут вернем как и в других местах их итерфейс.

2023-08-11 09:06 UTC, API-kernel commented on src/CodeChecker/Database/Repos/Interfaces/ICoursesRepo.cs
> +	public Task<CourseModel?> GetCourseByRepoUrlAndBranchAsync(string repoUrl, string branch);
Давай не будем дублироваться в нейминге, и если мы находимся в контексте CoursesRepo, то кажется что можно опускать упоминания  Course в именах методов. Ибо у тебя вызов и так будет сoursesRepo.GetCourseByRepoUrlAndBranchAsync(), кажется можно опустить до сoursesRepo.GetByRepoUrlAndBranchAsync()

2023-08-11 09:08 UTC, API-kernel commented on src/CodeChecker/Database/Repos/CourseVersionsRepo.cs
> +	public async Task<bool> CourseVersionExistsAsync(int courseId, string versionHash)
Может добавим Is?

2023-08-11 09:12 UTC, API-kernel commented on src/CodeChecker/Database/Entity/Interfaces/ICourseVersion.cs
> +	/// <summary>
Меня смущает что комменты дублируется в ICourseVersion и в CourseVersion

2023-08-11 09:13 UTC, API-kernel commented on src/CodeChecker/Database/Entity/Course.cs
> +	[Required]
Кажется оно если не nullable то оно и есть Required, не?

2023-08-11 09:16 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +	[HttpGet, Route("schema/{version}")]
тут можно сократить до [HttpGet("schema/{version}")]

2023-08-11 09:16 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +	private const string SchemasDirectoryName = "Schemas";
А у нас одинаковые настройки стоят, у меня райдер говорит что нужно переименовать в SCHEMAS_DIRECTORY_NAME

2023-08-11 09:18 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +	public async Task<ActionResult> GetScheme(string version)
Не хочется контроллеры делать жирными, это не очень хороший тон, в нем должно быть поминимуму вызов других сервисов, но логики в нем самом не должно находится.

2023-08-11 09:18 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +		if (!cache.TryGetValue(schemaName, out byte[]? schemaTextBytes))
Такие if-ки тяжко читать, которые занимают 50% метода, давай поделим тут как-то на методы

2023-08-11 09:27 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +			await using var stream = assembly.GetManifestResourceStream(resourceName);
Есть ощущение что мы несколько зря оборачиваем в проверки проблемные случае, если мы так или иначе кидаемя ошибками потом. Я чет большого смысла не уидел. Сы так или иначе получим 500-ю и у нас в целом будет стек и по нему можно будет с большой долей вероятночти это же и определеить. 

Просто чем больше кода тем больше вероятности ошибки, тем сложнее поддерживать... тут конечно вопрос про баланс. Я бы сместил его в сторону простоты кода в этом случае.

Мне кажется что участок чтения потока уместен и в таком виде

			var assembly = Assembly.GetExecutingAssembly();
			var resourceName = $"{assembly.GetName().Name}.{SCHEMAS_DIRECTORY_NAME}.{schemaName}.xsd";

			await using var stream = assembly.GetManifestResourceStream(resourceName);
			schemaTextBytes = await stream.ReadContentAsync();

2023-08-11 09:28 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Controllers/V1/WebhookController.cs
> +public class WebhookController : BaseCourseLoaderController
Давай тут тоже и контроллеров все спрячем за зависимости, котроллеры должны быть тонкими все же

2023-08-11 09:34 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +		return new DirectoryInfo($".{slash}{coursesPath}{slash}{courseModel.Team.Name}{slash}{courseModel.Course.Name}");
nit: Кажется так приятнее читать + это работает везде 

     return new DirectoryInfo($"./{coursesPath}/{courseModel.Team.Name}/{courseModel.Course.Name}");

2023-08-11 09:36 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +		if (!Directory.Exists(coursesPath))
А почему мы создаем дирректорию до coursesPath, но не создаем до  $"./{coursesPath}/{courseModel.Team.Name}/{courseModel.Course.Name}" ?

2023-08-11 09:38 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +	private DirectoryInfo GetCourseDirectory(CourseModel courseModel)
Смущает что у **Get**CourseDirectory есть артефакт в виде создание директорий в ФС, это не ожидаемое поведение.  Возможно стоит просто заинлайнить метод, вроде выглядит нормально при этом


	private async Task<CourseLoadingContext?> PrepareContext(GitRepoRecord gitRepoRecord)
	{
		var courseModel = await coursesRepo.GetCourseByRepoUrlAndBranchAsync(gitRepoRecord.RepoUrl, gitRepoRecord.Branch);
		if (courseModel == null) return null;

		var coursesPath = configurationProvider.Get<Settings.CourseLoaderSettings>().CoursesPath;

		if (!Directory.Exists(coursesPath)) Directory.CreateDirectory(coursesPath);

		var courseDirectory = new DirectoryInfo($"./{coursesPath}/{courseModel.Team.Name}/{courseModel.Course.Name}");
		return new CourseLoadingContext(courseModel, courseDirectory);
	}

2023-08-11 09:39 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +		var courseInfo = await coursesRepo.GetCourseByRepoUrlAndBranchAsync(gitRepoRecord.RepoUrl, gitRepoRecord.Branch);
Давай неминг держать одинаковый, если это CourseModel то и назвать либо сourse либо CourseModel

2023-08-11 09:40 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +			log.Warn(error);
А это не уровень ошибки? Я бы хотел это видеть в сентри кажется.

2023-08-11 09:41 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +	public async Task<bool> TryLoadCourse(GitRepoRecord gitRepoRecord)
Я не увидел большого смысла в выделении GitRepoRecord , кажется так или иначе эта штука быстро распадается на составляющие + их всего две... на твоё усмотрение.

2023-08-11 09:42 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +		var localRepoExists = context.LocalCourseDirectory.Exists && context.LocalCourseDirectory.EnumerateDirectories().Any();
Хочется булевы переменные чтоб словно отвечали на вопрос, т.е. хочется видеть Is в начале.

2023-08-11 09:44 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +	private static readonly Func<DateTime, string, string> buildVersionString = (versionTimestamp, versionHash) => $"{versionTimestamp.ToSortable()}_{versionHash}";
Этот хэлпер очень легко теряется среди гигантов-методов, да и кажется её не место тут, давай в хэлперы это вынесем.

2023-08-11 09:47 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +using Database.Models;
Давай по всему проекту удалим через райдер неиспльзуемые юзиги

2023-08-11 09:48 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +		var isVersionPublished = versionHash == context.Model.CourseVersion?.VersionHash;
Звучит крайне абстрактно `context.Model`, давай все же CourseModel назовем как CourseModel или Course

2023-08-11 12:42 UTC, Rozentor commented on src/CodeChecker/CodeChecker.CommonApi/BaseInstaller.cs
> +public static class BaseInstaller
CommonInstaller нужен для api и sandbox
BaseInstaller разрабатывался паралелльно первому, думаю лучше для course-loader я просто уберу BaseInstaller и сделаю там копипасту

2023-08-11 12:54 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +	private const string SchemasDirectoryName = "Schemas";
Хм, у меня не подсвечивает

2023-08-11 12:55 UTC, Rozentor commented on src/CodeChecker/CodeChecker.CommonApi/BaseApplication.cs
> +			webApplicationBuilder.Host.ConfigureContainer<IWindsorContainer>((_, container) => { InstallWindsor(_, container, environment); });
Тоже автоформатирование

2023-08-11 13:40 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +	public async Task<ActionResult> GetScheme(string version)
Вынесу в SchemaCacheHelper, который будет возвращать null если не нашёл схему

2023-08-11 13:40 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +		if (!cache.TryGetValue(schemaName, out byte[]? schemaTextBytes))
Вынесу в SchemaCacheHelper

2023-08-11 13:54 UTC, API-kernel requested changes

2023-08-11 13:54 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Git/GitRepoLoader.cs
> +public class GitRepoLoader : IGitRepoLoader
Название как-то не соответствует тому что он делает. Это вроде не сосем лоадер получается.

2023-08-11 13:54 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Git/GitShWorker/GitShWorker.cs
> +	private static string FindShPath()
Ох-хо-хох... ну штош. видимо другого пути-то у нас и нет с этой либой

2023-08-11 13:54 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Git/GitShWorker/GitShWorker.cs
> +		var shProcess = new Process();
Давай выделим создание процесса в отдельный метод, а то больно большой текущий получается

2023-08-11 13:54 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Git/Hub/GithubPushData.cs
> +	[DataMember(Name = "ref")] public string Ref;
Меня немного смущаю разные подходы к атрибутам, если посмотреть EF, то там мы над полем делаем. Может одинаково сделаем? PS в настройках которые я показывал, там вроде как это зашито.

2023-08-11 13:54 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Secret/SecretKeysProvider.cs
> +	public async Task<string?> GetPrivateKey(string teamName, string courseName)
Метод не выглядит асинхронным, может сделать его обычным тогда?

2023-08-11 13:54 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Secret/SecretKeysProvider.cs
> +		if (!deployKeys.TryGetValue(teamName.ToLower(), out var courseDeployKeys))
Нет желания составной ключ сделать? TEAM_KEY

Так-то большой разницы нет, это все равно потом поедет в vault )

2023-08-11 14:02 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Controllers/V1/WebhookController.cs
> +public class WebhookController : BaseCourseLoaderController
1. да, это копипаста + авто рефактор rider-а
2. вытаскивать из контроллера зависимости - ок, но не тогда, когда это обработка Request-а, контроллер должен запросы обрабатывать

3*. здесь можно вытащить валидацию секрета гита + если для каждой команды его сделать, так вообще точно отдельный класс

Предлагаю дополнить функционал, для каждого курса свой secret и вынесу отдельный класс

2023-08-11 14:12 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Exceptions/CourseLoadingException.cs
> +	public CourseLoadingException(string message, Exception? innerException = null)
Думал сюда завернуть информацию о курсе
+ говорящее название

2023-08-11 14:12 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Exceptions/GitException.cs
> +public class GitException : Exception
Копипаста из ulearn + MayBeSSHException - сигнал о том, что проблема в deploy key, а не в чём-то другом

2023-08-11 14:14 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Git/GitRepoLoader.cs
> +public class GitRepoLoader : IGitRepoLoader
Ну он загружает репозиторий)
Вроде как другого и не скажешь

2023-08-11 14:16 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Secret/SecretKeysProvider.cs
> +	public async Task<string?> GetPrivateKey(string teamName, string courseName)
Интерфейсно для запроса из vault-а
Думаю можно оставить и так

2023-08-11 14:16 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Secret/SecretKeysProvider.cs
> +		if (!deployKeys.TryGetValue(teamName.ToLower(), out var courseDeployKeys))
Пока нет желания, жду vault

2023-08-14 06:39 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Xml/Exercise/ExerciseXmlLoader.cs
> +		var exerciseXmlInfos = exercisesXmlPaths
Давай тут как-то побьём на методы, получение exerciseXmlInfos, построение Exercise, тогда метод будет выглядеть приятнее/читабельнее. Основной метод у меня вот такой получился:

	public IEnumerable<Database.Entity.Exercise> LoadExercises(CourseLoadingContext context, string[] exercisesXmlPaths)
	{
		var exerciseXmlInfos = ExerciseXmlInfos(context, exercisesXmlPaths);
		var exercisesIds = new HashSet<string>();

		foreach (var exerciseXmlInfo in exerciseXmlInfos)
		{
			var exerciseXml = GetExerciseXml(exerciseXmlInfo);

			if (exercisesIds.Contains(exerciseXmlInfo.Name))
				throw new CourseLoadingException($"Error while loading exercise.xml «{exerciseXmlInfo.Name}». " +
												$"Found exercise duplicate. Exercises should have uniq names. " +
												$"Loaded exercises are: «{string.Join(", ", exercisesIds)}»");

			exercisesIds.Add(exerciseXmlInfo.Name);

			yield return BuildExercise(context, exerciseXmlInfo, exerciseXml);
		}
	}

2023-08-14 06:43 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Xml/CodeFile/CodeFileLoader.cs
> +		var solutionFilePattern = $"{Path.GetFileNameWithoutExtension(userCodeFile.Name)}.solution{userCodeFile.Extension}";
Меня немного смущает что мы теряем информацию о пути до файла с решением, кажется его нужно положить в ExerciseMetadata

2023-08-14 06:44 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Xml/Exercise/ExerciseXml.cs
> +	public string ExerciseName { get; set; }
Можем ли мы имя формировать из названия файла?

2023-08-14 06:49 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Xml/Exercise/ExerciseXml.cs
> +	public string ExerciseDirName { get; set; }
Вот этот параметр мне не очень понятен, где/зачем он используется.

У нас еще видимо есть вопрос по размещение/формат курса в самой репе... типа где что лежит.

2023-08-14 06:51 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Xml/SchemaHelper.cs
> +	public const string SchemeLocationLocal = @"http://localhost:8134/course-loader/v1/schema/v1";
Так, а тут никак низя в рантайме эту штуку формировать? Тогда можно было бы из конфига брать. Оочень не хочется обмазывать это условной компиляцией.

2023-08-14 06:55 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Dockerfile
> +RUN apt-get -y update
В докер файлах обычно экономят на вызываемых командах, ибо каждая такая создаёт новый слой в нем.

Поэтому давай тут схлопнем эти команды через && \

2023-08-14 08:09 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Workers/CourseUpdateWorker.cs
> +		var coursesRepo = scope.ServiceProvider.GetService<ICoursesRepo>();
Давай тут вызовем GetRequiredService, и не будем кидаться ошибками сами... зачем писать код, если можно этого не делать

2023-08-14 08:15 UTC, API-kernel commented on src/CodeChecker/appsettings.json
> +	"CoursesPath": "./Courses",
Это все должно подтянуться из H само, предлагаю не дублировать настройки

2023-08-14 08:15 UTC, API-kernel commented on src/CodeChecker/appsettings.json
> +	"ConnectionString": "Host=localhost;Port=5432;Database=code-checker;Username=code-checker;Password=code-checker",
Это нужно положить в appsettings.dev.json

2023-08-14 08:18 UTC, API-kernel commented on src/CodeChecker/CodeChecker.CommonApi/ProxyHelper.cs
> +public static class ProxyHelper
HoustonIdentity  PortHelper ProxyHelper... чет слишком разбили, становится сложно ориентироваться.

Давай создадим класс настроек для приложения в H, там будут все необходимые поля собранные в одном месте. Ну и соотвественно нужно место где будут хранится два инстанса этого класса для  CourseLoader и API

2023-08-14 08:20 UTC, API-kernel commented on src/CodeChecker/CodeChecker.CommonApi/ProxyHelper.cs
> +public static class ProxyHelper
А, ну HoustonIdentity  получается он останется

2023-08-14 08:23 UTC, API-kernel commented on src/CodeChecker/CodeChecker.CommonApi/BaseApplication.cs
> +public abstract class BaseApplication : VostokAspNetCoreWebApplication
А API будем переводить на него? Кажется что сразу нужно это делать

2023-08-16 10:53 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Xml/Exercise/ExerciseXml.cs
> +	public string ExerciseName { get; set; }
Тогда надо будет из имени файла убирать (пре)постфикс
Пример

В курсе есть xml с заданиями и просто xml, которые как-то в заданиях используются
В course.xml указываем, что xml с заданиями это *.exercise.xml, чтобы не обрабатываеть ненужные xml
Тогда ExerciseName надо будет вычеслять из разницы с маской

Ещё аргументы:
Добавить 1 строчку в xml не сложно и не лень, при разработке задания это минимальная затрата.
Если я просто переименовал xml файл, он поменяется и в вызове api? - не очевидно, легко пропустить

2023-08-16 10:55 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Xml/Exercise/ExerciseXml.cs
> +	public string ExerciseDirName { get; set; }
xml файл внутрь папки не стоит класть, из примера выше
В папке потенциально может быть любой xml
Зачем туда добавлять *мусор* в виде xml с заданием, который потом на этапе сборки зипы надо будет убирать?
Опять прокидывать маску?

2023-08-16 10:57 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Xml/SchemaHelper.cs
> +	public const string SchemeLocationLocal = @"http://localhost:8134/course-loader/v1/schema/v1";
Тут должно быть только 1
Это схема из прода, исчезнет когда будет
Засунуть в конфиг можно, чтобы было ближе к правилам публикации H2
Но я пока не вижу в этом большой пользы

2023-08-16 11:03 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Helpers/ZipHelper.cs
> +	private static string[] GetEntryNames(IReadOnlyList<string>? names, string? sourceFolder, bool includeBaseName)
Это копипаста для создания зип файла
Лучше бы это переписать без создания файла на диске

2023-08-16 11:23 UTC, Rozentor commented on src/CodeChecker/CodeChecker.CommonApi/BaseApplication.cs
> +public abstract class BaseApplication : VostokAspNetCoreWebApplication
Там есть подключение JWT токена
Фильтр
Аутентификация - авторизация 

Как-то не хочется делать много virtual методов, которые потом будут переопределять, ещё в названии надо будет думать в какой-то момент метод вызовется

2023-08-16 15:02 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Helpers/ZipHelper.cs
> +	private static string[] GetEntryNames(IReadOnlyList<string>? names, string? sourceFolder, bool includeBaseName)
Но пока оставил так

2023-08-17 06:46 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/Xml/CodeFile/CodeFileLoader.cs
> +		var solutionFilePattern = $"{Path.GetFileNameWithoutExtension(userCodeFile.Name)}.solution{userCodeFile.Extension}";
Тогда нужно ли поле HasCreatorSolution? Кажется hasCreatorSolution = Path != null

2023-08-17 08:16 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/CodeChecker.Common.csproj
> +	  <ProjectReference Include="..\Database\Database.csproj" />
Есть проблема, CodeChecker.Common используется в песочнице, там нет БД. Становится страшно жить, что я могу где-то внедрить зависимость от БД и это у меня развалится в песочнице.

2023-08-17 08:18 UTC, API-kernel commented on src/CodeChecker/CodeChecker.CommonApi/BaseInstaller.cs
> +public static class BaseInstaller
Ага, давай заинлайним

2023-08-17 08:25 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Controllers/V1/WebhookController.cs
> +public class WebhookController : BaseCourseLoaderController
В контроллере все не должно быть что-то сложнее чем просто вызов пары зависимостей. Котроллеры сложно тестировать, котроллеры это не мето для логики - это лишьточка входа. Приватные методы в контроллерах это явно признак смешивания ответственностей.

2023-08-17 08:48 UTC, Rozentor commented on src/CodeChecker/CodeChecker.Common/CodeChecker.Common.csproj
> +	  <ProjectReference Include="..\Database\Database.csproj" />
Это изменения не из моей ветки
Так было раньше

Вижу что единственное исползование в FileLanguageHelper

2023-08-17 08:49 UTC, Rozentor commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveGateway.cs
> +	private const string DRIVE_SERVICE_ID = "ulearn-code-checker";
А мы не хотим DRIVE_SERVICE_ID  в конфиг?

2023-08-17 09:10 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Git/GitRepoLoader.cs
> +public class GitRepoLoader : IGitRepoLoader
Что я вижу по сигнатуре: IGitRepoLoader.GetLastCommitInfo из названия не скажешь что у тебя загружается репа.
Возможно тогда название класса норм. но значит название метода не норм.

2023-08-17 09:18 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Git/GitShWorker/GitShWorker.cs
> +		var shProcess = new Process();
Чет мы конечно не сильно много вынесли, я конечно же про вынесений все что связано с этим процессом.
Метод просто очень сильно перегружен, очень много деталей в одном месте, это сложно читать/поддерживать.

Основной метод вижу примерно таким:


	private async Task PerformOperation(
		string command,
		string gitOperationAdditionalFlags,
		string repoDir,
		string pathToPemKey,
		string gitRepoUrl
	)
	{
		if (!Directory.Exists(repoDir))
			Directory.CreateDirectory(repoDir);

		var shProcess = ShProcess(out var errorBuilder);

		await shProcess.StandardInput.WriteLineAsync($"{bashCommands}");

		var repoLoadingTimeoutInMinutes = configurationProvider.Get<GitSettings>().CourseLoadingTimeoutInMinutes;
		var timeout = Task.Delay(TimeSpan.FromMinutes(repoLoadingTimeoutInMinutes));
		await Task.WhenAny(shProcess.WaitForExitAsync(), timeout);

		shProcess.CancelOutputRead();
		shProcess.CancelErrorRead();

		if (timeout.IsCompleted)
			throw new TimeoutException("Git repo download timeout!");

		if (shProcess.ExitCode != 0 || errorBuilder.Length > 0)
			throw new Exception(errorBuilder.ToString());
	}

Можно чуть подумать, может что-то лучше чем `out var errorBuilder` можно сделать это мне просто райдер предложил

2023-08-17 09:19 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Git/Hub/GithubRepository.cs
> +	[DataMember(Name = "ssh_url")] public string SshUrl;
Давай единообразно отформатируем

2023-08-17 09:22 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Secret/SecretKeysProvider.cs
> +	public async Task<string?> GetPrivateKey(string teamName, string courseName)
Мне кажется преждевременно делать это все же не стоит. Когда нужно будет, это делается в пару нажатий zat+enter. Сейчас это выглядит очень странно.

2023-08-17 09:23 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Xml/CodeFile/CodeFileLoader.cs
> +		var solutionFilePattern = $"{Path.GetFileNameWithoutExtension(userCodeFile.Name)}.solution{userCodeFile.Extension}";
Возможно не нужно, можно кажется и убрать

2023-08-17 09:30 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Xml/Course/CourseXmlLoader.cs
> +		CourseXml courseXml;
Подобные конструкции очень просто переделываются в человеческие вынесением в отдельный методы

	public Database.Entity.Exercise[] LoadExercisesFromCourse(CourseLoadingContext context)
	{
		var courseXml = GetCourseXml(context);

		return exerciseXmlLoader
			.LoadExercises(context, courseXml.Exercises)
			.ToArray();
	}

	private static CourseXml GetCourseXml(CourseLoadingContext context)
	{
		try
		{
			var file = context.LocalCourseDirectory.GetFile(COURSE_XML_FILE_NAME);
			if (!file.Exists)
				throw new CourseLoadingException($"{COURSE_XML_FILE_NAME} doesn't exists at the root of course");

			return file.DeserializeXml<CourseXml>();
		}
		catch (Exception e)
		{
			throw new CourseLoadingException($"Error while reading {COURSE_XML_FILE_NAME}", e);
		}
	}

Также за счет этого мы изолируем "независимые" участки кода друг от друга. Читать/поддерживать становится проще.

2023-08-17 09:32 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Xml/Exercise/ExerciseXml.cs
> +	public string ExerciseDirName { get; set; }
Думаю можно пока сделать максимально похожим на ulearn, потом посмотрим как это все в конечном счёте будет выглядеть

2023-08-17 09:48 UTC, API-kernel commented on src/CodeChecker/Database/Repos/CourseVersionsRepo.cs
> +	public async Task<int> AddAsync(int courseId, DateTime versionTimestamp, string versionHash)
меня немного смутило что мы по-разному добавляем в репозитории сущности, где-то через прокидывание всего, где-то через прокидывание самих сущностей. Мне больше по душе второй вариант. Может однотипно сделаем?

2023-08-17 09:50 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Helpers/SchemaCacheHelper.cs
> +	public SchemaCacheHelper(ILog log, IMemoryCache cache, IConfigurationProvider configurationProvider)
О, оказалось что log тут не нужен

2023-08-17 09:52 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Helpers/ZipHelper.cs
> +	private static string[] GetEntryNames(IReadOnlyList<string>? names, string? sourceFolder, bool includeBaseName)
ок, давай пока оставим

2023-08-17 09:57 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Settings/GitSettings.cs
> +	public string Secret { get; set; }
А давай чуть более говорящее имя параметра придумает, а то звучит сильно абстрактно

2023-08-17 10:07 UTC, API-kernel commented on src/CodeChecker/Api/Controllers/V1/ExerciseController.cs
> +		var exerciseRoute = new ExerciseRoute(course.TeamId, course.CourseId, course.LastPublishedCourseVersionId.Value, exerciseName);
Сейчас мы туда положили ourse.LastPublishedCourseVersionId.Value, смешав ответственности.

Смотри, так как это именно Route, то ожидается что туда мапятся только данные из Route.
Так например посмотри в SolutionController, там в экшенах они используются именно для этого... и поле CourseVersionId явно там лишнее и явно придет к проблемам/ошибкам

2023-08-17 10:08 UTC, API-kernel commented on src/CodeChecker/Api/Controllers/V1/ExerciseController.cs
> +		var team = await teamsRepo.GetByTeamNameAsync(teamName);
Все еще актуально на самом деле

2023-08-17 10:10 UTC, API-kernel commented on src/CodeChecker/Database/Repos/Interfaces/IExerciseRepo.cs
> +	Task AddRangeAsync(IEnumerable<Exercise> exercises);
там местами еще есть этот хаос, можешь посмотреть в диффах, давай в новом коде везде заменим

2023-08-17 10:15 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Settings/GitSettings.cs
> +	public string Secret { get; set; }
Он переехал в бд WebhookSecret
Надо убрать

2023-08-17 10:16 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Controllers/V1/SchemaController.cs
> +		if (!cache.TryGetValue(schemaName, out byte[]? schemaTextBytes))
Стало хорошо

2023-08-17 10:20 UTC, API-kernel commented on src/CodeChecker/Database/Entity/Course.cs
> +	[Required]
А что с другими полями? Давай там тоже уберем тогда?

2023-08-17 10:22 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Exceptions/GitException.cs
> +public class GitException : Exception
кажется подозрительным, ну да ладно, хочешь. давай оставим

2023-08-17 10:24 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/CodeChecker.Common.csproj
> +	  <ProjectReference Include="..\Database\Database.csproj" />
Эм, смотрю в нашу основную ветку, там этого нет: https://github.com/kontur-edu/Ulearn/blob/feature/code-checker/src/CodeChecker/CodeChecker.Common/CodeChecker.Common.csproj

Ну и дифф же... или че?

2023-08-17 10:53 UTC, Rozentor commented on src/CodeChecker/CodeChecker.Common/CodeChecker.Common.csproj
> +	  <ProjectReference Include="..\Database\Database.csproj" />
А, вижу, понял
Переместил пока в CourseLoader, где используется
Потом подумаем куда ещё можно деть

Изначально в ulear он лежал в Common, вот и переехал также:)

2023-08-17 11:05 UTC, Rozentor commented on src/CodeChecker/Api/Controllers/V1/ExerciseController.cs
> +		var team = await teamsRepo.GetByTeamNameAsync(teamName);
Мне кажется пока можно это сохранить в таком виде, а когда появится необходимость сделать похожее - вытаскивать

2023-08-17 11:25 UTC, API-kernel commented on src/CodeChecker/CodeChecker.CommonApi/BaseInstaller.cs
> +public static class BaseInstaller
Все еще жив

2023-08-17 12:13 UTC, API-kernel commented on src/CodeChecker/Database/Models/Exercises/ExerciseRoute.cs
>  public record ExerciseRoute(
Давай тогда уже откатим изменения, а точнее вернем ToString

2023-08-17 12:20 UTC, API-kernel commented on src/CodeChecker/Api/Controllers/V1/ExerciseController.cs
> +		var team = await teamsRepo.GetByTeamNameAsync(teamName);
Мне просто что не понравилось, то что в контроллере появляется какая-то логика, причем с высоким потенциалом переиспользования. И кажется нужно такие штуки сразу выносить в отдельные провайдеры. 

Вообще я не очень понимаю почему этот участок кода уже не используется в сущ. методах в SolutionController.

Ну и да, получается что уже можно сказать что дублируем функционал SolutionValidator.
Давай обобщим код ну и адаптируем методы из SolutionController для работы с новой схемой БД.

2023-08-17 12:21 UTC, API-kernel commented on src/CodeChecker/Database/Repos/Interfaces/IExerciseRepo.cs
> +	Task AddRangeAsync(IEnumerable<Exercise> exercises);
- IExerciseXmlLoader

2023-08-21 11:56 UTC, API-kernel commented on src/CodeChecker/Api/Controllers/V1/ExerciseController.cs
>  	private readonly ITeamRepo teamRepo;
Давай удалим неиспользуемые зависимости

2023-08-21 12:03 UTC, API-kernel commented on src/CodeChecker/Api/Models/Validators/ValidationResult.cs
> +public record ValidationResult(ActionResult? InvalidResult = null);
Я не увидел профита от record, наследование всегда сложнее/дороже чем интерфейсы, давай через них сделаем

2023-08-21 12:07 UTC, API-kernel commented on src/CodeChecker/Api/Models/Validators/Interfaces/IExerciseValidator.cs
> +public interface IExerciseValidator : IValidator<ExerciseValidationResult, ExerciseRoute>
Кажется это должно уйти, если отказаться от наследования в пользу интерфейсов

2023-08-21 12:09 UTC, API-kernel commented on src/CodeChecker/Api/Models/Validators/SolutionValidator.cs
> +		if (System.Text.Encoding.Unicode.GetByteCount(file.Code) > MAX_FILE_SIZE.Kb())
Я там в основной ветке заменил `System.Text.Encoding.Unicode` на 'System.Text.Encoding.UTF8'.

Осторожно при мердже, возможно лучше сразу поправить.

2023-08-21 12:19 UTC, Rozentor commented on src/CodeChecker/Api/Models/Validators/Interfaces/IExerciseValidator.cs
> +public interface IExerciseValidator : IValidator<ExerciseValidationResult, ExerciseRoute>
Это просто сокращение для читаемости
А изменить IValidator не получится, нужно в него вкладывать и то, что он валидирует, и результат

2023-08-21 12:21 UTC, Rozentor commented on src/CodeChecker/Api/Models/Validators/ValidationResult.cs
> +public record ValidationResult(ActionResult? InvalidResult = null);
IValidationResult сделать просто
Но вот его наследников SolutionValidationResult и ExerciseValidationResult вроде не поменять

2023-08-21 12:22 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/Git/GitShWorker/GitShWorker.cs
>  		var shellExeFileName = FindShPath();
Может тогда тоже внутрь засунуть? Вроде не причин из вне передавать

2023-08-21 12:41 UTC, API-kernel commented on src/CodeChecker/Api/Models/Validators/ValidationResult.cs
> +public record ValidationResult(ActionResult? InvalidResult = null);
Я не вижу проблем

2023-08-21 12:43 UTC, API-kernel commented on src/CodeChecker/Api/Models/Validators/ValidationResult.cs
> +public record ValidationResult(ActionResult? InvalidResult = null);
https://github.com/kontur-edu/Ulearn/commit/bf1a6ce323bb9093bd3c67cf1f3f7997916ea8a2

2023-08-21 12:46 UTC, Rozentor commented on src/CodeChecker/Api/Models/Validators/ValidationResult.cs
> +public record ValidationResult(ActionResult? InvalidResult = null);
То есть что хочется в итоге?)
SolutionValidationResult и ExerciseValidationResult становятся интерфейсами?

2023-08-21 14:43 UTC, merged