ULEARN-1146 Модуль автопровеки кода. Прогрев файлов курса
kontur-edu/Ulearn pull request #353
Opened 2023-08-31 08:13 UTC by API-kernel

2023-08-31 12:36 UTC, LuKas-03 commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +		if (DateTime.UtcNow - creationTime < 10.Minutes())
А может разруливать это семафорами? т.е. если семафор на папку захвачен, значит кто-то что там делает (идёт распаковка новой версии, например) и эту папку лучше не трогать

2023-08-31 12:36 UTC, LuKas-03 commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseCacheMeta.cs
> +	public DirectoryInfo? LastDownloadedVersion => DateTime.UtcNow - UpdateDatetime > 1.Hours() ? null : Version;
я так понимаю этот `1.Hours()` и [Scheduler.Periodical(TimeSpan.FromHours(1))](https://github.com/kontur-edu/Ulearn/pull/353/files#diff-db8e0601d4b4815c3bcb02236f5ac6f7e1f9e9e071f8dd7a39d59a2d27377c23R26) выше связаны. Может их явно связать общей константой?

2023-08-31 12:36 UTC, LuKas-03 commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +		if (DateTime.UtcNow - creationTime < 10.Minutes())
Ну и получается семафоры нужно будет инкапсулировать из CourseLocalDirectoryManager

2023-08-31 12:36 UTC, LuKas-03 commented on src/CodeChecker/Readme.md
>      "ConnectionString": "Host=localhost;Port=5432;Database=CodeChecker;Username=postgres;Password=postgres",
некрасиво съехало )
предлагаю аналогично юзать пробелы ну или везде поменять на табы

2023-08-31 12:51 UTC, Rozentor requested changes

2023-08-31 12:51 UTC, Rozentor commented on src/CodeChecker/Api/ApiWorker.cs
> +public class ApiWorker : VostokScheduledApplication
Тут вроде только про кэш курсов идет речь
Api слишком абстрактно

2023-08-31 12:51 UTC, Rozentor commented on src/CodeChecker/Database/Repos/CoursesRepo.cs
> +	public async Task<CourseModel[]> GetAllAsync()
Я в своей ветке это использовал, мне не нужен CourseModel
Кажется сейчас появляется каша между ICourse и CourseModel

1. не стоит менять их, лучше переименовать метод и/или создать новый
2. подумать бы как это в названии отображать, когда хочется сделать одно и тоже, но получить разное

2023-09-01 06:38 UTC, API-kernel commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +		if (DateTime.UtcNow - creationTime < 10.Minutes())
Можно, и первые мысли были именно такими, но показалось что два словаря семофоров это сильное усложнение кода, и кажется шанс накосячить там очень велик. А одним не пулучается обойтись, т.к. текущий словарь он на основе ID курсов, и так вроде и должно быть, т.к. это неизменяемый идентификатор, что не скажешь про имя. А в случае работы с ФС, там мы храним имена курсов.

Мне показалось что если не трогать новые папки, то это и просто выглядит и надежно (Даже если выкачивание будет длиться больше 10 минут, то мы все равно не удалим его, ибо версия значит уже будет в БД, в теории тут можно поставить гораздо меньший интервал, например в минуту)

Мне показало что что такая проверка более уместная чем еще пачка семафоров.

2023-09-01 06:41 UTC, API-kernel commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseCacheMeta.cs
> +	public DirectoryInfo? LastDownloadedVersion => DateTime.UtcNow - UpdateDatetime > 1.Hours() ? null : Version;
Не, они не связаны, давай тут вообще в 1 день выставим.

Тут указывается период сколько можно ходить в старую версию пока нет новой.

А там про периодичность запуска удаление старых версий.

2023-09-01 06:47 UTC, API-kernel commented on src/CodeChecker/Readme.md
>      "ConnectionString": "Host=localhost;Port=5432;Database=CodeChecker;Username=postgres;Password=postgres",
Поправил

2023-09-01 06:48 UTC, API-kernel commented on src/CodeChecker/Api/ApiWorker.cs
> +public class ApiWorker : VostokScheduledApplication
Я бы не хотел в название включать упоминание про кэш. Это просто воркер, сюда можно добавлять любые таски, т.е. он не специфичен для кэш, поэтому кажется что абстрактное название тут уместно.

2023-09-01 06:51 UTC, API-kernel commented on src/CodeChecker/Readme.md
>      "ConnectionString": "Host=localhost;Port=5432;Database=CodeChecker;Username=postgres;Password=postgres",
Поворот, а у нас на уровне всего проекта включены табы, а не пробелы =(

2023-09-01 11:02 UTC, API-kernel commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +		if (DateTime.UtcNow - creationTime < 10.Minutes())
Так накидал новую версию, на 10-ю итерацию я осознал что все же удаление не нужно локать, если мы зафиксируем список директорий, а потом составим список используемых версий, то можно не обращать внимание на ново загружаемые версии. Кажется учел все варианты (но мне кажется это самообман)

2023-09-01 11:06 UTC, API-kernel commented on src/CodeChecker/Database/Repos/CoursesRepo.cs
> +	public async Task<CourseModel[]> GetAllAsync()
1. У меня есть ощущение что в большинстве случаев нужно работать с моделью, и крайне редко нужна не она, а голая ICourse. Поэтому решил именно переделать метод.
2. Это на самом деле просто, нужно всего лишь видимо в одно случае писать `GetAllModelsAsync` в другом  `GetAllAsync`

2023-09-01 11:08 UTC, API-kernel commented on src/CodeChecker/Database/Repos/CoursesRepo.cs
> +	public async Task<CourseModel[]> GetAllAsync()
Ну давай верну, если что в твоем коммите уберем

2023-09-01 11:09 UTC, API-kernel commented on src/CodeChecker/Api/ApiWorker.cs
> +public class ApiWorker : VostokScheduledApplication
Не получилось убедить, ок, пусть будет CourseLocalDirectoryWorker и будем под каждую зависимость городить воркеры

2023-09-01 12:31 UTC, Rozentor requested changes

2023-09-01 12:31 UTC, Rozentor commented on src/CodeChecker/Api/CourseLocalDirectoryWorker.cs
> +			scheduler: Scheduler.Crontab("0 0 * * *"),//Каждый день в 0:00
Комментарий в коде - неговорящий код
Давай
EverydayMidnight = "..."
Или подобное :)

2023-09-01 12:31 UTC, Rozentor commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +			TryDelete(new CourseVersionDir(version));
Хм, немного странно выглядит

Delete(new ())

Может переместить в Select выше? Там же ещё Contains с new

2023-09-01 12:31 UTC, Rozentor commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseVersionDir.cs
> +        Path = new DirectoryInfo(path)
private DirectoryInfo dir;

Init
dir = new DirectoryInfo(path)
Path = dir.FullName...;

IsExists => dir.Exists (св-во вместо метода, меньше писать ())
Create => ...

2023-09-01 12:31 UTC, Rozentor commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseVersionDir.cs
> +        Path = new DirectoryInfo(path)
Вообще кажется что этот record это просто обвязка над DirectoryInfo в который мы закрыли доступ ко всему и добавили Path
Будто хочется лишний код не делать, вынести extension для path
Почему хочется инкапсулировать?

2023-09-01 12:31 UTC, Rozentor commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +		await Task.Delay(10.Seconds());
Хочется сказать "Эвристика!", но возможно этого и так хватит

2023-09-01 12:35 UTC, Rozentor commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +		await Task.Delay(10.Seconds());
Да, доп. код не хочется писать

2023-09-01 12:50 UTC, LuKas-03 commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +		if (DateTime.UtcNow - creationTime < 10.Minutes())
такая ситуация может ещё произойти: если одновременно скачивается 2+ версии курса (2+ коммита подряд сделали, например). Тогда папки версий последней из БД и последней полноценно скачанной тронуты не будут, но при этом промежуточные будут удалены, не закончив распаковываться. Но возможно это и не проблема т.к. очень маловероятно + эти версии всё равно не будут использоваться, а через сутки удалятся окончательно

2023-09-04 06:14 UTC, API-kernel commented on src/CodeChecker/Api/CourseLocalDirectoryWorker.cs
> +			scheduler: Scheduler.Crontab("0 0 * * *"),//Каждый день в 0:00
Не понял почему он не говорящий вроде в точности говорит что делается в коде, не?

ок, поправил

2023-09-04 06:17 UTC, API-kernel commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +			TryDelete(new CourseVersionDir(version));
Ага, проглядел во время рефакторинга, теперь создается CourseVersionDir один  раз

2023-09-04 06:23 UTC, API-kernel commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseVersionDir.cs
> +        Path = new DirectoryInfo(path)
Не хочу чтоб наружу был просто string, он не гарантирует ничего, что там полный путь, что там все в нижнем регистре, что правильные слеши -- это все потенциальные проблемы. Поэтому это отдельный класс, который гарантирует правильность имени. DirectoryInfo как свойство я не хочу, дабы в статический словарь (LastDownloadedVersions) не попадала вся эта жирная структура + мне не очевидно что она не будет удерживать внешние ресуры во время совей работы. 

Пусть IsExists и Create останутся методами, тогда становится очевиднее это это вычисляемы штуки, а не просто значения. + Create void поэтому нельзя будет сделать его методом, а хочется чтоб они были одинаковыми, ибо в них особой разницы нет.

2023-09-04 06:33 UTC, API-kernel commented on src/CodeChecker/Api/Infrastructure/LocalCache/CourseLocalCacheRemover.cs
> +		if (DateTime.UtcNow - creationTime < 10.Minutes())
Ага, вроде нет проблемы в то что они пролежат еще денёк

2023-09-04 07:23 UTC, Rozentor approved these changes

2023-09-04 13:53 UTC, merged