Ulearn-1156
kontur-edu/Ulearn pull request #354
Opened 2023-08-31 21:45 UTC by Rozentor

2023-09-01 12:18 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveGateway.cs
> +	public async Task<DeleteResult> DeleteAsync(string name)
Из контракта не очевидно что DeleteAsync принимает полный путь в драйве, в то время как остальные методы относительные.

2023-09-01 12:25 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +		using var _ = new OperationContextToken($"gitRepoUrl={gitRepoRecord.RepoUrl}:{gitRepoRecord.Branch}");
Возможно стоит просто залогировать, вроде если везде ниже будет teamName\courseName то этого достаточно.

Там просто gitRepoRecord.RepoUrl будет длинным, кажется в логах потом не очень читабельно все это будет

2023-09-01 12:32 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +			throw;
Немного смутило повторное пробрасывание ошибки, возможно просто тут залогирвоdать сам ex, + тут тоже возвращать true|false. Мне кажется так код легче воспринимать, когда меньше нужно мотаться по методам.

Ну и вроде ожидаемо получить стек трейc по ошибке вместе с `log.Error("Error while adding new version, ensuring corrupted data is removed");`

Еще не понятно почему в сетри при этом должно быть два события (раз два `log.Error`)

2023-09-01 12:41 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +					var publishedCourseVersion = course.CourseVersion!;
Ух табы, как же с вами тяжело... уже хочу заменить все на пробелы =)

2023-09-01 12:45 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +		using var _ = new OperationContextToken($"gitRepoUrl={gitRepoRecord.RepoUrl}:{gitRepoRecord.Branch}");
Будет длинным, да
Но что если обновили git repo url?
Странно, но возможно

Предлагаю 1 раз залогировать, чтобы не терять данные

2023-09-01 12:48 UTC, API-kernel commented on src/CodeChecker/Database/Repos/Interfaces/ICoursesRepo.cs
>  	Task<ICourse[]> GetAllAsync();
Вроде он не понадобился тебе в итоге, видимо нужно будет выпилить где-то?)

2023-09-01 12:50 UTC, Rozentor commented on src/CodeChecker/Database/Repos/Interfaces/ICoursesRepo.cs
>  	Task<ICourse[]> GetAllAsync();
Да, выпилит тот, у кого позже мерд будет :D

2023-09-01 12:55 UTC, API-kernel commented on src/CodeChecker/Database/Repos/ExerciseRepo.cs
> +	public async Task RemoveCourseVersionExercises(int courseVersionId)
У нас ведь новейший EF7! Смотри как тут можно

	public async Task RemoveCourseVersionExercises(int courseVersionId)
	{
		await using var db = new CodeCheckerDbContext();

		await db.Exercises
			.Where(e => e.CourseVersionId == courseVersionId)
			.ExecuteDeleteAsync();
	}

2023-09-01 12:55 UTC, API-kernel commented on src/CodeChecker/Database/Repos/CourseVersionsRepo.cs
> +		await using var db = new CodeCheckerDbContext();
Давай тут тоже удаление сделаем без доп. похода в БД

2023-09-01 12:57 UTC, Rozentor commented on src/CodeChecker/Database/Repos/ExerciseRepo.cs
> +	public async Task RemoveCourseVersionExercises(int courseVersionId)
!!!
Я использовал Z.EntityFramework.Extensions.EFCore DeleteFromQuery и совсем забыл про ef7

2023-09-01 12:58 UTC, API-kernel commented on src/CodeChecker/Database/Entity/Interfaces/ICourseVersion.cs
> +	DateTime CreationTime { get; }
У нас где-то уже есть подобное поле, там оно носит имя CreatedDateTime, может также назовем?

2023-09-01 13:03 UTC, API-kernel commented on src/CodeChecker/CourseLoader/CourseLoaderApplication.cs
> +		//builder.AddHostedServiceFromApplication<CourseUpdateWorker>();
комментарий детектед

2023-09-01 13:03 UTC, Rozentor commented on src/CodeChecker/CourseLoader/CourseLoaderApplication.cs
> +		//builder.AddHostedServiceFromApplication<CourseUpdateWorker>();
Очепятка после тестов, исправлю

2023-09-01 13:04 UTC, API-kernel commented on src/CodeChecker/CourseLoader/CourseLoaderApplication.cs
> +			webApplicationBuilder.Services.Configure<JsonOptions>(options => { options.SerializerOptions.Converters.Add(new JsonStringEnumConverter()); });
Ох, тут снова автоформатирование напортачило (

2023-09-01 13:06 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Workers/CoursesCleanupWorker.cs
> +		CleanupCourses().GetAwaiter().GetResult();
Мне кажется можно не нагружать сервис при запуске, пусть удаляет только в час Х.
Возможно еще нужно не просто каждый день, а делать это ночью, дабы минимизировать ущерб/меньше мешаться другим и т.п.

2023-09-01 13:07 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/ICourseVersionsCleaner.cs
> +	Task RemoveDriveCourseVersionAsync(string driveUrl);
Я думаю можно убрать из имен методов `CoursesVersions` это будет понятно из контекста вызова, ибо у нас зависимость так называется

2023-09-01 13:35 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		foreach (var course in allCourses)
Мне кажется что такая конструкция довольно опасна, может все же добавим скобки?

2023-09-01 13:40 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		if (driveVersions.Any())
Нас на CLoud может начать ошибками забрасывать из-за локальных курсов, это норм не норм?

2023-09-01 13:42 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		var dbVersions = await courseVersionsRepo.GetAllByCourseAsync(courseModel.Course);
Давай тут по id будем искать, вроде нет причин весь курс туда кидать

2023-09-01 13:44 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		if (driveVersions.Any())
DriveVersions - это соотвествие по команде-курсу
Может закидать, да

Мне кажется надо для local делать приписку в путях драйва

2023-09-01 13:47 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		var driveVersions = driveRequest
Ожидался предварительный вызов driveRequest.EnsureSuccess();

2023-09-01 13:49 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +				return new DriveCourseVersion(courseVersion, url);
Выглядит странным, создание DriveCourseVersion с пустым courseVersion, кажется что такие не должны создаваться

2023-09-01 13:50 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +				return new DriveCourseVersion(courseVersion, url);
Именно так мы и узнаем о зипках без версии в бд
В нормальном случае таких быть не должно

2023-09-01 13:54 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +			.ToDictionary(c => c.VersionHash);
Нет, такого быть не должно
Доказательство на скрине
![image](https://github.com/kontur-edu/Ulearn/assets/36932390/ee27dc3f-4cf4-4502-97bf-c001f9fa2499)

2023-09-04 05:43 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +				return new DriveCourseVersion(courseVersion, url);
Дабы не путаться в путях, относительные они ли абсолютные, есть предложение оперировать только одним типом

2023-09-04 05:48 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +	private bool EnsureValidity(ICourseVersion[] dbVersions, DriveCourseVersion[] driveVersions)
Я думаю тут нужно удалять то что мы можем удалять, а то мы так сломаемся на одной зипке и постоянно будем скипать этот курс, это не есть гуд.

2023-09-04 05:50 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		log.Info("Removing course zip from drive");
Кажется тут не лишним будет указать путь до курса в драйве

2023-09-04 05:50 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		log.Info("Removing exercises and course version from db");
А тут возможно будет не лишним указать версию

2023-09-04 05:52 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +			await RemoveDbCourseVersionAsync(current.CourseVersion.CourseVersionId);
Кажется тут можно обернуть в try-catch, дабы проблемы с одной версией не мешали удалять другие версии, аналогично хочется и для списка курсов сделать.

2023-09-04 05:56 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveHelper.cs
> +	public static string GetVersionHashFromCourseZipPath(string courseZipUrl)
Выглядит немного опасным, в том плане что если match не произойдет

2023-09-04 06:02 UTC, Rozentor commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveHelper.cs
> +	public static string GetVersionHashFromCourseZipPath(string courseZipUrl)
Поэтому он находится максимально близко к второму месту, где используется такой формат

2023-09-04 06:02 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveHelper.cs
> +		var pathRegex = new Regex(@$"srv\/{DRIVE_SERVICE_ID}\/teams\/(.+)\/(.+)\/(.+)_(.+)\.zip");
Тут можно Teams взять из константы

2023-09-04 06:03 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		log.Info("Removing exercises and course version from db");
Она есть в OpeartionToken

2023-09-04 06:03 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		log.Info("Removing course zip from drive");
Он есть в OpeartionToken

2023-09-04 06:03 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +	private bool EnsureValidity(ICourseVersion[] dbVersions, DriveCourseVersion[] driveVersions)
Мы же обсуждали
Такие курсы нуждаются в ручной обработке, т.к. должны быть редким событием

2023-09-04 07:16 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +				return new DriveCourseVersion(courseVersion, url);
Здесь имеется в виду driveName
это не полный url, но полное название внутри драйва (srv/{project}/etc)

2023-09-05 06:36 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseLoader.cs
> +			var courseVersion = new CourseVersion { CourseId = context.CourseModel.Course.CourseId, VersionTimestamp = versionTimestamp, VersionHash = versionHash, CreatedDateTime = DateTime.UtcNow };
Давай поля разнесем каждое в новую строчку, а то так читается код сложно

2023-09-05 06:42 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveGateway.cs
> +	public async Task<DeleteResult> DeleteAsync(string name)
Я не очень понял что поменялось, ожидалось что внутри метода будет как и в других местах оборачиваться в GetFullName(name)

2023-09-05 06:49 UTC, API-kernel commented on src/CodeChecker/Database/Repos/Interfaces/ICoursesRepo.cs
>  	Task<ICourse[]> GetAllAsync();
видимо в этом коммите )

2023-09-05 09:30 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Workers/CoursesCleanupWorker.cs
> +		var everydayMidnightScheduler = Scheduler.Crontab("0 0 * * *");
Теперь можно заюзать константу

2023-09-05 09:37 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +			using var _ = new OperationContextToken($"driveUrl={current.DriveCourseVersion!.DriveName}");
Тут та же самая проблема, в логах, записи будут сильно раздуваться из-за пути в драйве, кажется по courseVersionId в целом можно все восстановить будет

2023-09-05 09:40 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +			if (successor.CourseVersion!.CreatedDateTime + 1.Days() > DateTime.UtcNow)
nit: вроде проще воспринимать как successor.CourseVersion!.CreatedDateTime > DateTime.UtcNow - 1.Days()

2023-09-05 10:05 UTC, API-kernel requested changes

2023-09-05 10:05 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +				return new DriveCourseVersion(courseVersion, url);
Ага, это и смущает, что у нас есть два пути которыми мы оперируем в приложении, и однозначно определить это по типу невозможно. Это уже просочилось в интерфесы методов и это меня сильно смущает что одним методы с такими путями работают, другие с другими

2023-09-05 10:05 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +	private bool EnsureValidity(ICourseVersion[] dbVersions, DriveCourseVersion[] driveVersions)
Нужно подумать про тест, в нем мне совсем не нравится ситуация из-за локальных баз у разработчиков

2023-09-05 10:10 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		if (driveVersions.Any())
Нужно придумать как решать проблему на cloud где у каждого может быть своя БД и разработчик может запустить сервисы локально

2023-09-05 10:21 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		if (driveVersions.Any())
А почему мы не можем удалять только те данные о которых мы точно знаем, т.е. вот у нас есть версии, допустим в какой-то момент мы принимаем решение об её удалении, у удаляем его из бд  и драйва. Профит.

2023-09-05 12:05 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		var successor = orderedVersions[0];
Не усложнение, а пропуск опубликованной версии, нам с ней делать нечего (Skip(1))
successor - более новая версия относительно current

_Пустой список_
Такого быть не может, ведь тогда CourseVersion = null
А если не null, тогда он либо есть в драйве, либо отловится раньше

2023-09-08 12:08 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		if (driveVersions.Any())
Теперь не закидает, потому что берутся версии только в соотвествии с бд

2023-09-12 10:10 UTC, API-kernel commented on sandboxes/python-sandbox/container/Dockerfile
> +	&& apt-get install -y gcc && apt-get install -y nano && rm -rf /var/lib/apt/lists/*
А почему мы поменяли питоновый образ? Не ожидал это видеть в рамках этой задачи

2023-09-12 10:47 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		var successor = orderedVersions[0];
Все еще не понял смысла настолько усложнять код.. заниматься мутацией переменных, высчитывать индексы, потом скипать элементы по этому индексу... зачем такие сложности? Этого ведь всего не нужно. Давай в коде отразим именно то, что мы хотим сделать.

В частности мы хотим выбрать все версии которые старше одно дня, ну дак давай это и напишем:

		var outdatedVersions = courseVersionsWithDrive
			.Where(v => v.CourseVersion.CreatedDateTime < DateTime.UtcNow - 1.Days())
			.ToArray();

Все становится сразу очевидным, не запутывая читателей кода. Мест где накосяить практически нет, что не сказать об тек. решении.

2023-09-12 10:58 UTC, Rozentor commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +			.Skip(versionSuccessor + 1)
Потому что 0 это индекс текущей опубликованной версии и мы её не хотим удалять

2023-09-12 11:03 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Workers/CoursesCleanupWorker.cs
> +		using var _ = new OperationContextToken(nameof(CoursesCleaner));
Что-то подобное уже будет в контексте (CleanupCourses), это добавляет сам Schedule. Давай уберем.

2023-09-12 11:05 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Workers/CoursesCleanupWorker.cs
> +		log.Info($"Start {nameof(CoursesCleaner)};");
О, оказывает восточный шаблон тоже пишет в лог инфу о запуске, поэтому возможно можно и убрать эту строчку.

2023-09-12 11:11 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Helpers/CourseVersionsHelper.cs
> +					var pathV = parsedPath.Value;
Смущает название, может просто path уж тогда?

2023-09-12 11:18 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Helpers/CourseVersionsHelper.cs
> +	public async Task<(ICourseVersion[] courseVersions, DriveCourseVersion[] driveCourseVersions)> GetVersionsAsync(CourseModel courseModel)
А зачем нам такие сложности сейчас? Давай уберем вообще DriveCourseVersion, оставим тут только ICourseVersion. По факту, на они не нужны, если не считать EnsureNoVersionsExist, но этот метод он довольно редко используемый и больше информативный нежели чем несет полезную нагрузку, и для него держать этот код я не вижу смысла.

2023-09-12 11:20 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Helpers/CourseVersionsHelper.cs
> +	public async Task<(ICourseVersion[] courseVersions, DriveCourseVersion[] driveCourseVersions)> GetVersionsAsync(CourseModel courseModel)
Т.е. у нас что будет. Ищем старые версии курсов, идем удалять их из бд и удалям из из драйва, профит.

Просто, понятно, безопасно.

2023-09-12 11:27 UTC, API-kernel commented on src/CodeChecker/CourseLoader/Core/CourseVersionsCleaner/CourseVersionsCleaner.cs
> +		var successor = orderedVersions[0];
Исходя из соседних тредов стало понятно что тут еще и тек. версия передается, и из-за неё было это все сделано. 

Кажется исключать самую свежую версию по дате, выглядит не самым очевидным образом, и больше похоже на то что мы опираемся на какие-то следствия фактов, а не на них самих. Предлагаю явно это выразить в коде, например получив актуальные версии отдельным методом.

2023-09-13 11:39 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveGateway.cs
> +	public async Task<DownloadResult<ContentMetadataResponse[]>> GetAllMetadataByPrefixAsync(string prefix)
Давай дропнем метод

2023-09-13 11:41 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveHelper.cs
> +public static class DriveHelper
Давай откатим до предыдущего состояния?

2023-09-13 11:49 UTC, API-kernel commented on src/CodeChecker/CodeChecker.Common/Library/Drive/DriveNameHelper.cs
> +	public static string PathToTeam(string teamName) => $"{TEAMS}/{teamName}".ToLower();
Осталось много новых, публичных, неиспользуемых методов, давай вернём как было:

```
	private const string DRIVE_SERVICE_ID = "ulearn-code-checker";

	public static string SolutionZip(Guid submissionId) => SolutionZip(submissionId.ToString());
	public static string SolutionZip(string submissionId) => $"solution-zip/{submissionId}.zip".ToLower();
	public static string CourseZip(string teamName, string courseName, string version) => $"teams/{teamName}/{courseName}/{version}.zip".ToLower();

	public static string GetFullName(string name)
	{
		return new EntityNameBuilder()
			.SetServiceId(DRIVE_SERVICE_ID)
			.SetName(name)
			.GetName();
	}
```

2023-09-13 12:18 UTC, merged